FROM python:3.10-slim

WORKDIR /app

COPY requirements.api.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY code /app/code
COPY models /app/models

EXPOSE 8000

CMD ["uvicorn", "code.deployment.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
