version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: celeba-api:latest
    container_name: celeba-api
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/docs')"]
      interval: 10s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: celeba-app:latest
    container_name: celeba-app
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
